liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        logo_login:
            quality: 75
            default_image: /img/HVGLOGO.jpg
            filters:
                upscale: { min: [800, 600] }
                thumbnail: { size: [800, 600], mode: outbound }
        member_photography_small:
            quality: 75
            default_image: /uploads/member/BomberoDefaultSmall.jpg
            filters:
                upscale: { min: [80, 100] }
                thumbnail: { size: [80, 100], mode: outbound }
        member_photography_medium:
            quality: 75
            default_image: /uploads/member/BomberoDefault.jpg
            filters:
                upscale: { min: [460, 600] }
                thumbnail: { size: [460, 600], mode: outbound }
        member_photography_large:
            quality: 75
            default_image: /uploads/member/BomberoDefault.jpg
            filters:
                upscale: { min: [920, 1200] }
                thumbnail: { size: [920, 1200], mode: outbound }

        resource_photography_small:
            quality: 75
            filters:
                upscale: { min: [140, 80] }
                thumbnail: { size: [140, 80], mode: outbound }
        resource_photography_medium:
            quality: 75
            filters:
                upscale: { min: [530, 300] }
                thumbnail: { size: [530, 300], mode: outbound }
        resource_photography_large:
            quality: 75
            filters:
                upscale: { min: [920, 1200] }
                thumbnail: { size: [920, 1200], mode: outbound }

        history_photography_small:
            quality: 75
            filters:
                upscale: { min: [80, 80] }
                thumbnail: { size: [80, 80], mode: outbound }
        history_photography_medium:
            quality: 75
            filters:
                upscale: { min: [640, 420] }
                thumbnail: { size: [640, 420], mode: outbound }
        history_photography_large:
            quality: 75
            filters:
                upscale: { min: [920, 1200] }
                thumbnail: { size: [920, 1200], mode: outbound }

        notice_photography_small:
            quality: 75
            filters:
                upscale: { min: [140, 80] }
                thumbnail: { size: [140, 80], mode: outbound }
        notice_photography_medium:
            quality: 75
            filters:
                upscale: { min: [640, 420] }
                thumbnail: { size: [640, 420], mode: outbound }
        notice_photography_large:
            quality: 75
            filters:
                upscale: { min: [1280, 720] }
                thumbnail: { size: [1280, 720], mode: outbound }

        main_photography_small:
            quality: 75
            filters:
                upscale: { min: [80, 80] }
                thumbnail: { size: [80, 80], mode: outbound }
        main_photography_medium:
            quality: 75
            filters:
                upscale: { min: [500, 500] }
                thumbnail: { size: [500, 500], mode: outbound }
        main_photography_large:
            quality: 75
            filters:
                upscale: { min: [1900, 700] }
                thumbnail: { size: [1900, 700], mode: outbound }

        frontpage_gallery_modal:
            quality: 75
            default_image: /uploads/photography/default.jpg
            filters:
                thumbnail: { size: [1280, 1280], mode: inset }
                watermark:
                    image: ../web/uploads/photography/watermark.png
                    size: 0.5
                    position: center