klan_page_testing:
    resource: "@KlanPageBundle/Resources/config/routing/testing.yml"
    prefix:   /testing

klan_page_homepage:
    path:     /
    defaults: { _controller: KlanPageBundle:Default:index }
